<?php

namespace Api\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{
    use SoftDeletes;

    protected $table = 'users';
    protected $fillable = [
        'email', 'username', 'password'
    ];

    public const PASSWORD_HASH_TYPE = PASSWORD_BCRYPT;
    public static function HashPassword($password) {
        return password_hash($password, self::PASSWORD_HASH_TYPE);
    }

    public function fill(array $attributes) : User
    {
        if($attributes['password'])
            $attributes['password'] = self::HashPassword($attributes['password']);
        return parent::fill($attributes);
    }
    public function save(array $options = []) : bool
    {
        if($options['password'])
            $options['password'] = self::HashPassword($options['password']);
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}